#!/usr/bin/env perl

package path2uri;

use v5.40;

use lib 'lib';

use WWW::srvdir::Util qw'path2uri';
use Path::Tiny;
use Getopt::Long
  qw(GetOptionsFromArray :config no_ignore_case auto_abbrev passthrough bundling long_prefix_pattern=--?);
use IO::Handle::Common;

my @listfile = ();
my @path     = ();
my %cliopt = ( debug => $ENV{DEBUG}, outfile => undef, listfile => \@listfile );

GetOptions(
    \%cliopt,
    'debug+',
    'verbose+',
    'wrap-anchor|wrap-htmlelem',
    'outfile|output|writeto:s',
    'host|domain|fqdn:s',
    'replace-host', 'relative|no-host',
    'root|mount:s',
    'port|service:s',
    'unique',
    'list-file:s@', 'path|listfile|input-path=s@',
    '<>' => sub ($barearg) {
        push @listfile, $barearg;
    }
);

if ( !-t STDIN ) {
    @listfile = map { chomp $_; $_ } (<STDIN>);
}

dmsg \%cliopt;

my %opt = %cliopt{qw'unique host port vroot replace'};
foreach my ( $k, $v ) ( %cliopt{qw'wrap-anchor replace-host'} ) {
    $opt{ ( $k =~ s/-/_/gr ) } = $v;
}

my $htmlout = path2uri(
    [
        # grep { $_->is_file }
        map { chomp $_; $_ }
        map { try_path($_)->lines_utf8 } @listfile
    ],
    %cliopt{qw'unique host port vroot replace'}
);

if ( my $outfile = $cliopt{outfile} ) {
    $outfile = try_path($outfile)->spew_utf8($htmlout);
    success("Encoded links written to '$outfile'");
}
else {
    say $htmlout;
}
